# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-12-15 22:22:00
"""
import arcpy
from sys import argv
from datetime import date

path = r"G:\projects\UtilityDistricts\eweb\DrinkingWater\EPA319_NPS_grant\ForestApplication\ODF_FACTS_DB\FERNS\FERNS_Model"
wrkspace = path + "\\FERNS_Workspace.gdb"
year = str(date.today().year)

def FERNSforAGOstep2(Expression="YEAR = {0}".format(year)):  # FERNS for AGO step 2

    arcpy.env.overwriteOutput = True

    AGO_FERNSSummary_McKenzie_Joined_4_ = "AGO FERNSSummary_McKenzie_Joined"

    # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
    AGO_FERNSSummary_McKenzie_Joined_2_, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=AGO_FERNSSummary_McKenzie_Joined_4_, 
                                                                                        selection_type="NEW_SELECTION", 
                                                                                        where_clause=Expression, 
                                                                                        invert_where_clause="")

if __name__ == '__main__':
    # Global Environment settings
    # with arcpy.EnvManager(scratchWorkspace=wrkspace, workspace=wrkspace):
    #     FERNSforAGOstep2(*argv[1:])
    print("tested")