# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-12-15 22:22:00
"""
import arcpy
from sys import argv
from datetime import date
import timeit

path = r"G:\projects\UtilityDistricts\eweb\DrinkingWater\EPA319_NPS_grant\ForestApplication\ODF_FACTS_DB\FERNS\FERNS_Model"
wrkspace = path + "\\FERNS_Workspace.gdb"
year = str(date.today().year)

def FERNSforAGOstep2(Expression=f"YEAR = '{year}'"):  # FERNS for AGO step 2

    arcpy.env.overwriteOutput = True

    AGO_FERNSSummary_McKenzie_Joined_4_ = "https://services5.arcgis.com/9s1YtFmLS0YTl10F/arcgis/rest/services/FERNS_for_McKenzie_Catchments/FeatureServer/0"

    # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
    AGO_FERNSSummary_McKenzie_Joined_2_, count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=AGO_FERNSSummary_McKenzie_Joined_4_, 
                                                                                        selection_type="NEW_SELECTION", 
                                                                                        where_clause=Expression, 
                                                                                        invert_where_clause="")
    print(f"Year {year} has {count} counts!")

if __name__ == '__main__':
    start = timeit.default_timer()
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=wrkspace, workspace=wrkspace):
        FERNSforAGOstep2(*argv[1:])
    # print("tested")
    stop = timeit.default_timer()
    total_time = stop - start
    print(f'FERNS for AGO step 2 takes {total_time}')